name: Test

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - main

jobs:
  merge_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      id-token: write # Needed for OIDC and keyless signing
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Get changed files in the manifests folder
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: manifests/*.{yaml,yml}
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
    - name: Sign
      run: |
        curl -sLO https://github.com/sigstore/k8s-manifest-sigstore/releases/download/v0.4.3/kubectl-sigstore-linux-amd64
        chmod +x kubectl-sigstore-linux-amd64
        sudo mv kubectl-sigstore-linux-amd64 kubectl-sigstore
        ./kubectl-sigstore version
        ls -lah
        for file in ${{ steps.changed-files.outputs.all_changed_files }}
        do
          echo "Signing $f"
          COSIGN_EXPERIMENTAL=1 ./kubectl-sigstore sign --tarball=no -f $file -o $file
        done
    - name: Commit
      run: |
        git add manifests/\*
        git commit --signoff -m "chore: sign manifests"
        git push

  clean_unsigned:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    needs: merge_job
    permissions:
      contents: write
      actions: read
      id-token: write # Needed for OIDC and keyless signing
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Remove all unsigned manifests
      run: |
        echo "Clearing contents of unsigned directory."
        rm unsigned/*
    - name: Push removal of unsigned manifests
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        commit: --signoff
        push: --set-upstream origin signed --force
        add: -A unsigned/
        default_author: github_actions
        message: 'Cleaned unsigned manifests.'
